import { bigint, boolean, date, integer, pgSchema, text, timestamp, uuid } from 'drizzle-orm/pg-core';

// Drizzle definitions of the stock ledger's tables (stock-ledger 14.2; code-house-rules 3.4). They mirror the reviewed
// migration (migrations/organisation/0026) and never create or change a table; an integration test compares each
// with the migrated database. Never exported from the unit's index.ts (code-house-rules 2). Amounts are integer paise
// (PRD-MOD-014); a null amount, SKU or brand is Unknown (PRD-MOD-015). A header row's brand set is `brand_ids`
// (stock-ledger 14.1; DEC-117).

const stock = pgSchema('stock');

const at = (name: string) => timestamp(name, { withTimezone: true, mode: 'date' });

export const unitAnchor = stock.table('unit_anchor', {
  id: uuid('id').primaryKey(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const receiptOrigin = stock.table('receipt_origin', {
  id: uuid('id').primaryKey(),
  originKind: text('origin_kind').notNull(),
  parentOriginId: uuid('parent_origin_id'),
  sourceModule: text('source_module').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRecordId: uuid('source_record_id').notNull(),
  sourceVersionId: uuid('source_version_id').notNull(),
  sourceLineId: uuid('source_line_id').notNull(),
  sourceImportKind: text('source_import_kind').notNull(),
  skuId: uuid('sku_id'),
  skuVersionId: uuid('sku_version_id'),
  stockUnit: text('stock_unit').notNull(),
  pieceTracked: boolean('piece_tracked').notNull(),
  batchTracked: boolean('batch_tracked').notNull(),
  batchCode: text('batch_code'),
  expiryDate: date('expiry_date'),
  quantity: integer('quantity').notNull(),
  countDate: date('count_date').notNull(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  mappingVersionId: uuid('mapping_version_id').notNull(),
  bookId: uuid('book_id').notNull(),
  occurredAt: at('occurred_at').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const movement = stock.table('movement', {
  id: uuid('id').primaryKey(),
  kind: text('kind').notNull(),
  sourceModule: text('source_module').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRecordId: uuid('source_record_id').notNull(),
  sourceVersionId: uuid('source_version_id').notNull(),
  sourceLineId: uuid('source_line_id').notNull(),
  sourceImportKind: text('source_import_kind').notNull(),
  actorUserId: uuid('actor_user_id'),
  actorServiceIdentityId: uuid('actor_service_identity_id'),
  onBehalfOfUserId: uuid('on_behalf_of_user_id'),
  roleAssignmentId: uuid('role_assignment_id').notNull(),
  approvalUseId: uuid('approval_use_id'),
  reversesMovementId: uuid('reverses_movement_id'),
  correctionOfMovementId: uuid('correction_of_movement_id'),
  businessDate: date('business_date').notNull(),
  occurredAt: at('occurred_at').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandIds: uuid('brand_ids').array().notNull(),
});

export const movementLeg = stock.table('movement_leg', {
  id: uuid('id').primaryKey(),
  movementId: uuid('movement_id').notNull(),
  direction: text('direction').notNull(),
  receiptOriginId: uuid('receipt_origin_id').notNull(),
  skuId: uuid('sku_id'),
  quantity: integer('quantity').notNull(),
  locationId: uuid('location_id'),
  condition: text('condition').notNull(),
  heldAs: text('held_as').notNull(),
  transitKind: text('transit_kind'),
  transitRef: uuid('transit_ref'),
  batchCode: text('batch_code'),
  expiryDate: date('expiry_date'),
  bookId: uuid('book_id').notNull(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const skuBalance = stock.table('sku_balance', {
  id: uuid('id').primaryKey(),
  siteId: uuid('site_id').notNull(),
  businessUnitId: uuid('business_unit_id').notNull(),
  skuId: uuid('sku_id'),
  stockUnit: text('stock_unit').notNull(),
  quantity: integer('quantity').notNull(),
  storeId: uuid('store_id'),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const balance = stock.table('balance', {
  id: uuid('id').primaryKey(),
  skuBalanceId: uuid('sku_balance_id').notNull(),
  siteId: uuid('site_id').notNull(),
  businessUnitId: uuid('business_unit_id').notNull(),
  locationId: uuid('location_id'),
  condition: text('condition').notNull(),
  heldAs: text('held_as').notNull(),
  transitKind: text('transit_kind'),
  transitRef: uuid('transit_ref'),
  skuId: uuid('sku_id'),
  batchCode: text('batch_code'),
  expiryDate: date('expiry_date'),
  receiptOriginId: uuid('receipt_origin_id').notNull(),
  countDate: date('count_date').notNull(),
  quantity: integer('quantity').notNull(),
  acceptedQuantity: integer('accepted_quantity').notNull(),
  storeId: uuid('store_id'),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const piece = stock.table('piece', {
  id: uuid('id').primaryKey(),
  code: text('code').notNull(),
  skuId: uuid('sku_id'),
  receiptOriginId: uuid('receipt_origin_id').notNull(),
  locationId: uuid('location_id'),
  condition: text('condition').notNull(),
  heldAs: text('held_as').notNull(),
  transitKind: text('transit_kind'),
  transitRef: uuid('transit_ref'),
  inCustody: boolean('in_custody').notNull(),
  ptRevisionId: uuid('pt_revision_id'),
  acceptedSiteId: uuid('accepted_site_id'),
  lastMovementId: uuid('last_movement_id'),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const movementPiece = stock.table('movement_piece', {
  id: uuid('id').primaryKey(),
  movementId: uuid('movement_id').notNull(),
  pieceId: uuid('piece_id').notNull(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const receiptOriginState = stock.table('receipt_origin_state', {
  id: uuid('id').primaryKey(),
  receiptOriginId: uuid('receipt_origin_id').notNull(),
  ownerKind: text('owner_kind'),
  ownerLegalEntityId: uuid('owner_legal_entity_id'),
  ownerPartyId: uuid('owner_party_id'),
  ownerBrandId: uuid('owner_brand_id'),
  agreementVersionId: uuid('agreement_version_id'),
  valueKnown: boolean('value_known').notNull(),
  pRatePaise: bigint('p_rate_paise', { mode: 'number' }),
  establishedValuePaise: bigint('established_value_paise', { mode: 'number' }),
  originQuantity: integer('origin_quantity').notNull(),
  ptRevisionId: uuid('pt_revision_id'),
  coveredQuantity: integer('covered_quantity').notNull(),
  lastStateMovementId: uuid('last_state_movement_id').notNull(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const coverage = stock.table('coverage', {
  id: uuid('id').primaryKey(),
  ptRevisionId: uuid('pt_revision_id').notNull(),
  receiptOriginId: uuid('receipt_origin_id').notNull(),
  pieceTracked: boolean('piece_tracked').notNull(),
  pieceId: uuid('piece_id'),
  quantity: integer('quantity').notNull(),
  action: text('action').notNull(),
  removesCoverageId: uuid('removes_coverage_id'),
  sourceModule: text('source_module').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRecordId: uuid('source_record_id').notNull(),
  sourceVersionId: uuid('source_version_id').notNull(),
  sourceLineId: uuid('source_line_id').notNull(),
  sourceImportKind: text('source_import_kind').notNull(),
  actorUserId: uuid('actor_user_id'),
  actorServiceIdentityId: uuid('actor_service_identity_id'),
  onBehalfOfUserId: uuid('on_behalf_of_user_id'),
  roleAssignmentId: uuid('role_assignment_id').notNull(),
  businessDate: date('business_date').notNull(),
  occurredAt: at('occurred_at').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
});

export const acceptance = stock.table('acceptance', {
  id: uuid('id').primaryKey(),
  receiptOriginId: uuid('receipt_origin_id').notNull(),
  pieceId: uuid('piece_id'),
  quantity: integer('quantity').notNull(),
  sourceModule: text('source_module').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRecordId: uuid('source_record_id').notNull(),
  sourceVersionId: uuid('source_version_id').notNull(),
  sourceLineId: uuid('source_line_id').notNull(),
  sourceImportKind: text('source_import_kind').notNull(),
  actorUserId: uuid('actor_user_id'),
  actorServiceIdentityId: uuid('actor_service_identity_id'),
  onBehalfOfUserId: uuid('on_behalf_of_user_id'),
  roleAssignmentId: uuid('role_assignment_id').notNull(),
  businessDate: date('business_date').notNull(),
  occurredAt: at('occurred_at').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
});

export const reservation = stock.table('reservation', {
  id: uuid('id').primaryKey(),
  kind: text('kind').notNull(),
  sourceModule: text('source_module').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRecordId: uuid('source_record_id').notNull(),
  sourceVersionId: uuid('source_version_id').notNull(),
  sourceLineId: uuid('source_line_id').notNull(),
  sourceImportKind: text('source_import_kind').notNull(),
  actorUserId: uuid('actor_user_id'),
  actorServiceIdentityId: uuid('actor_service_identity_id'),
  onBehalfOfUserId: uuid('on_behalf_of_user_id'),
  roleAssignmentId: uuid('role_assignment_id').notNull(),
  businessDate: date('business_date').notNull(),
  occurredAt: at('occurred_at').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandIds: uuid('brand_ids').array().notNull(),
});

export const hold = stock.table('hold', {
  id: uuid('id').primaryKey(),
  kind: text('kind').notNull(),
  reason: text('reason').notNull(),
  evidenceFileId: uuid('evidence_file_id'),
  withinReservationId: uuid('within_reservation_id'),
  sourceModule: text('source_module').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRecordId: uuid('source_record_id').notNull(),
  sourceVersionId: uuid('source_version_id').notNull(),
  sourceLineId: uuid('source_line_id').notNull(),
  sourceImportKind: text('source_import_kind').notNull(),
  actorUserId: uuid('actor_user_id'),
  actorServiceIdentityId: uuid('actor_service_identity_id'),
  onBehalfOfUserId: uuid('on_behalf_of_user_id'),
  roleAssignmentId: uuid('role_assignment_id').notNull(),
  businessDate: date('business_date').notNull(),
  occurredAt: at('occurred_at').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandIds: uuid('brand_ids').array().notNull(),
});

export const holdScope = stock.table('hold_scope', {
  id: uuid('id').primaryKey(),
  holdId: uuid('hold_id').notNull(),
  holdKind: text('hold_kind').notNull(),
  locationId: uuid('location_id'),
  scopeBrandId: uuid('scope_brand_id'),
  skuId: uuid('sku_id'),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandIds: uuid('brand_ids').array().notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const holdClaim = stock.table('hold_claim', {
  id: uuid('id').primaryKey(),
  holdId: uuid('hold_id').notNull(),
  pieceId: uuid('piece_id'),
  balanceId: uuid('balance_id'),
  quantity: integer('quantity').notNull(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const holdRelease = stock.table('hold_release', {
  id: uuid('id').primaryKey(),
  holdId: uuid('hold_id').notNull(),
  holdKind: text('hold_kind').notNull(),
  holdClaimId: uuid('hold_claim_id').notNull(),
  releaseEvent: text('release_event').notNull(),
  quantity: integer('quantity').notNull(),
  pieceId: uuid('piece_id'),
  sourceModule: text('source_module').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRecordId: uuid('source_record_id').notNull(),
  sourceVersionId: uuid('source_version_id').notNull(),
  sourceLineId: uuid('source_line_id').notNull(),
  sourceImportKind: text('source_import_kind').notNull(),
  actorUserId: uuid('actor_user_id'),
  actorServiceIdentityId: uuid('actor_service_identity_id'),
  onBehalfOfUserId: uuid('on_behalf_of_user_id'),
  roleAssignmentId: uuid('role_assignment_id').notNull(),
  businessDate: date('business_date').notNull(),
  occurredAt: at('occurred_at').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
});

export const reservationClaim = stock.table('reservation_claim', {
  id: uuid('id').primaryKey(),
  reservationId: uuid('reservation_id').notNull(),
  pieceId: uuid('piece_id'),
  balanceId: uuid('balance_id'),
  quantity: integer('quantity').notNull(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const reservationEvent = stock.table('reservation_event', {
  id: uuid('id').primaryKey(),
  reservationId: uuid('reservation_id').notNull(),
  reservationKind: text('reservation_kind').notNull(),
  reservationClaimId: uuid('reservation_claim_id').notNull(),
  event: text('event').notNull(),
  quantity: integer('quantity').notNull(),
  pieceId: uuid('piece_id'),
  movementId: uuid('movement_id'),
  sourceModule: text('source_module').notNull(),
  sourceRecordType: text('source_record_type').notNull(),
  sourceRecordId: uuid('source_record_id').notNull(),
  sourceVersionId: uuid('source_version_id').notNull(),
  sourceLineId: uuid('source_line_id').notNull(),
  sourceImportKind: text('source_import_kind').notNull(),
  actorUserId: uuid('actor_user_id'),
  actorServiceIdentityId: uuid('actor_service_identity_id'),
  onBehalfOfUserId: uuid('on_behalf_of_user_id'),
  roleAssignmentId: uuid('role_assignment_id').notNull(),
  businessDate: date('business_date').notNull(),
  occurredAt: at('occurred_at').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
});

export const costPool = stock.table('cost_pool', {
  id: uuid('id').primaryKey(),
  bookId: uuid('book_id').notNull(),
  skuId: uuid('sku_id').notNull(),
  poolMode: text('pool_mode').notNull(),
  siteId: uuid('site_id'),
  formula: text('formula').notNull(),
  costSettingVersionId: uuid('cost_setting_version_id').notNull(),
  quantity: integer('quantity').notNull(),
  valuePaise: bigint('value_paise', { mode: 'number' }).notNull(),
  lastSequence: bigint('last_sequence', { mode: 'number' }).notNull(),
  closedAt: at('closed_at'),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const transitValue = stock.table('transit_value', {
  id: uuid('id').primaryKey(),
  transitKind: text('transit_kind').notNull(),
  transitRef: uuid('transit_ref').notNull(),
  bookId: uuid('book_id').notNull(),
  skuId: uuid('sku_id').notNull(),
  quantity: integer('quantity').notNull(),
  valuePaise: bigint('value_paise', { mode: 'number' }).notNull(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const valuation = stock.table('valuation', {
  id: uuid('id').primaryKey(),
  movementId: uuid('movement_id').notNull(),
  receiptOriginId: uuid('receipt_origin_id').notNull(),
  costPoolId: uuid('cost_pool_id'),
  transitValueId: uuid('transit_value_id'),
  sequence: bigint('sequence', { mode: 'number' }),
  quantityDelta: integer('quantity_delta').notNull(),
  valueDeltaPaise: bigint('value_delta_paise', { mode: 'number' }).notNull(),
  quantityBefore: integer('quantity_before').notNull(),
  quantityAfter: integer('quantity_after').notNull(),
  valueBeforePaise: bigint('value_before_paise', { mode: 'number' }).notNull(),
  valueAfterPaise: bigint('value_after_paise', { mode: 'number' }).notNull(),
  eventKind: text('event_kind').notNull(),
  component: text('component').notNull(),
  businessDate: date('business_date').notNull(),
  accountingDate: date('accounting_date').notNull(),
  siteId: uuid('site_id'),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id'),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const costLayer = stock.table('cost_layer', {
  id: uuid('id').primaryKey(),
  costPoolId: uuid('cost_pool_id').notNull(),
  poolFormula: text('pool_formula').notNull(),
  enteredSequence: bigint('entered_sequence', { mode: 'number' }).notNull(),
  enteredAt: at('entered_at').notNull(),
  quantityIn: integer('quantity_in').notNull(),
  quantityLeft: integer('quantity_left').notNull(),
  valueInPaise: bigint('value_in_paise', { mode: 'number' }).notNull(),
  valueLeftPaise: bigint('value_left_paise', { mode: 'number' }).notNull(),
  fromLayerId: uuid('from_layer_id'),
  receiptOriginId: uuid('receipt_origin_id'),
  fromValuationId: uuid('from_valuation_id'),
  siteId: uuid('site_id'),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id').notNull(),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const valuationLayer = stock.table('valuation_layer', {
  id: uuid('id').primaryKey(),
  valuationId: uuid('valuation_id').notNull(),
  costLayerId: uuid('cost_layer_id').notNull(),
  pieceId: uuid('piece_id'),
  quantity: integer('quantity').notNull(),
  valuePaise: bigint('value_paise', { mode: 'number' }).notNull(),
  siteId: uuid('site_id'),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id'),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});

export const transitValueLayer = stock.table('transit_value_layer', {
  id: uuid('id').primaryKey(),
  transitValueId: uuid('transit_value_id').notNull(),
  sourceLayerId: uuid('source_layer_id').notNull(),
  quantity: integer('quantity').notNull(),
  valuePaise: bigint('value_paise', { mode: 'number' }).notNull(),
  siteId: uuid('site_id').notNull(),
  storeId: uuid('store_id'),
  businessUnitId: uuid('business_unit_id').notNull(),
  legalEntityId: uuid('legal_entity_id').notNull(),
  brandId: uuid('brand_id'),
  recordedAt: at('recorded_at').notNull().defaultNow(),
});
